#!/usr/bin/env bash

#######################################################################################
# NPM Wrapper
#
# Orginial script: https://www.bradcypert.com/simple-npm-wrapper-using-nvm/
#######################################################################################

# Versions
NVM_VERSION="0.36.0"
NODE_VERSION="14.14.0"

# Setup NVM
setup_nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

# Export these paths once so we can check if NVM exists.
setup_nvm

# Install nvm if necessary
if ! hash nvm 2>/dev/null; then
  curl -o- "https://raw.githubusercontent.com/creationix/nvm/v$NVM_VERSION/install.sh" | bash
fi

# Export again in case we had to install. Sometimes NVM doesnt do a good job manually exporting quick enough.
setup_nvm

# Install node version
nvm install $NODE_VERSION

# Execute the npm command
npm "$@"