name: Github Pages Deploy
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Github Ref'
        required: false
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: ./npmw install --no-fund --no-progress --loglevel=error
      - name: Build NPM Project
        if: success()
        run: ./npmw run build
      - name: Publish to Github Pages
        if: success()
        uses: jamesives/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
